In [1]:
import os
import pandas as pd

In [2]:
df = pd.read_csv('../../data/CheXpert-v1.0-small_raw/train.csv')

# Frontal views only (AP and PA)
df = df[df['Frontal/Lateral'] == 'Frontal']

# Extract patient_id from path
df['patient_id'] = df['Path'].str.extract(r'(patient\d+)')

# Extract study_id from path
df['study_id'] = df['Path'].str.extract(r'(study\d+)')

# Strip 'CheXpert-v1.0-small/' prefix to get path relative to data/CheXpert-v1.0-small_raw/
df['image'] = df['Path'].str.replace('CheXpert-v1.0-small/', '', regex=False)

df.head()

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,...,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,patient_id,study_id,image
0,CheXpert-v1.0-small/train/patient00001/study1/...,Female,68,Frontal,AP,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,1.0,patient00001,study1,train/patient00001/study1/view1_frontal.jpg
1,CheXpert-v1.0-small/train/patient00002/study2/...,Female,87,Frontal,AP,NaN,NaN,-1.0,1.0,NaN,...,NaN,-1.0,NaN,-1.0,NaN,1.0,NaN,patient00002,study2,train/patient00002/study2/view1_frontal.jpg
2,CheXpert-v1.0-small/train/patient00002/study1/...,Female,83,Frontal,AP,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,patient00002,study1,train/patient00002/study1/view1_frontal.jpg
4,CheXpert-v1.0-small/train/patient00003/study1/...,Male,41,Frontal,AP,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,patient00003,study1,train/patient00003/study1/view1_frontal.jpg
5,CheXpert-v1.0-small/train/patient00004/study1/...,Female,20,Frontal,PA,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,patient00004,study1,train/patient00004/study1/view1_frontal.jpg

In [3]:
# Positives: Pneumonia == 1.0 (exclude uncertain -1.0 and unmentioned NaN)
# One image per patient: keep the first study alphabetically
df_pos = df[df['Pneumonia'] == 1.0]
df_pos = df_pos.loc[df_pos.groupby('patient_id')['study_id'].idxmin()]

display(df_pos[['image', 'Sex', 'Age', 'AP/PA', 'Pneumonia']].describe())
df_pos

               Age  Pneumonia
count  3927.000000     3927.0
mean     62.478992        1.0
std      18.711350        0.0
min      18.000000        1.0
25%      50.000000        1.0
50%      64.000000        1.0
75%      78.000000        1.0
max      90.000000        1.0

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,...,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,patient_id,study_id,image
311,CheXpert-v1.0-small/train/patient00085/study1/...,Male,88,Frontal,AP,NaN,NaN,NaN,1.0,NaN,...,1.0,-1.0,NaN,NaN,NaN,NaN,NaN,patient00085,study1,train/patient00085/study1/view1_frontal.jpg
315,CheXpert-v1.0-small/train/patient00086/study1/...,Female,77,Frontal,AP,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,patient00086,study1,train/patient00086/study1/view1_frontal.jpg
390,CheXpert-v1.0-small/train/patient00112/study1/...,Male,35,Frontal,PA,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,patient00112,study1,train/patient00112/study1/view1_frontal.jpg
411,CheXpert-v1.0-small/train/patient00114/study15...,Male,55,Frontal,AP,NaN,NaN,NaN,1.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,1.0,patient00114,study15,train/patient00114/study15/view1_frontal.jpg
440,CheXpert-v1.0-small/train/patient00122/study5/...,Female,72,Frontal,AP,NaN,NaN,NaN,1.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,1.0,patient00122,study5,train/patient00122/study5/view1_frontal.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223251,CheXpert-v1.0-small/train/patient64398/study1/...,Male,39,Frontal,AP,NaN,NaN,NaN,1.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,patient64398,study1,train/patient64398/study1/view1_frontal.jpg
223292,CheXpert-v1.0-small/train/patient64435/study1/...,Female,64,Frontal,AP,NaN,NaN,NaN,1.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,patient64435,study1,train/patient64435/study1/view1_frontal.jpg
223322,CheXpert-v1.0-small/train/patient64462/study2/...,Female,49,Frontal,AP,NaN,1.0,NaN,1.0,NaN,...,1.0,1.0,NaN,1.0,NaN,NaN,1.0,patient64462,study2,train/patient64462/study2/view1_frontal.jpg
223373,CheXpert-v1.0-small/train/patient64505/study1/...,Female,50,Frontal,AP,NaN,NaN,NaN,1.0,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,1.0,patient64505,study1,train/patient64505/study1/view1_frontal.jpg
223378,CheXpert-v1.0-small/train/patient64509/study1/...,Male,41,Frontal,AP,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,patient64509,study1,train/patient64509/study1/view1_frontal.jpg

In [4]:
# Negatives: No Finding == 1.0, patients with a single study only
# (mirrors NIH logic of single follow-up patients)
study_counts = df.groupby('patient_id')['study_id'].nunique().reset_index()
study_counts.rename(columns={'study_id': 'n_studies'}, inplace=True)
single_study_patients = study_counts[study_counts['n_studies'] == 1]['patient_id']

df_neg = df[
    (df['patient_id'].isin(single_study_patients)) &
    (df['No Finding'] == 1.0)
]
# One image per patient
df_neg = df_neg.loc[df_neg.groupby('patient_id')['study_id'].idxmin()]

display(df_neg[['image', 'Sex', 'Age', 'AP/PA', 'No Finding']].describe())
df_neg

               Age  No Finding
count  7201.000000      7201.0
mean     48.348563         1.0
std      17.751788         0.0
min       0.000000         1.0
25%      34.000000         1.0
50%      48.000000         1.0
75%      61.000000         1.0
max      90.000000         1.0

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,...,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,patient_id,study_id,image
0,CheXpert-v1.0-small/train/patient00001/study1/...,Female,68,Frontal,AP,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,1.0,patient00001,study1,train/patient00001/study1/view1_frontal.jpg
5,CheXpert-v1.0-small/train/patient00004/study1/...,Female,20,Frontal,PA,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,patient00004,study1,train/patient00004/study1/view1_frontal.jpg
11,CheXpert-v1.0-small/train/patient00006/study1/...,Female,42,Frontal,AP,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,patient00006,study1,train/patient00006/study1/view1_frontal.jpg
18,CheXpert-v1.0-small/train/patient00010/study1/...,Female,50,Frontal,PA,1.0,0.0,NaN,0.0,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,patient00010,study1,train/patient00010/study1/view1_frontal.jpg
40,CheXpert-v1.0-small/train/patient00013/study1/...,Male,36,Frontal,PA,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,patient00013,study1,train/patient00013/study1/view1_frontal.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223388,CheXpert-v1.0-small/train/patient64519/study1/...,Female,33,Frontal,AP,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,1.0,patient64519,study1,train/patient64519/study1/view1_frontal.jpg
223389,CheXpert-v1.0-small/train/patient64520/study1/...,Female,65,Frontal,AP,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,patient64520,study1,train/patient64520/study1/view1_frontal.jpg
223391,CheXpert-v1.0-small/train/patient64522/study1/...,Female,21,Frontal,AP,1.0,NaN,0.0,0.0,NaN,...,NaN,NaN,0.0,0.0,NaN,NaN,0.0,patient64522,study1,train/patient64522/study1/view1_frontal.jpg
223402,CheXpert-v1.0-small/train/patient64532/study1/...,Female,52,Frontal,AP,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,1.0,patient64532,study1,train/patient64532/study1/view1_frontal.jpg
223413,CheXpert-v1.0-small/train/patient64540/study1/...,Female,0,Frontal,AP,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,patient64540,study1,train/patient64540/study1/view1_frontal.jpg

In [5]:
df_neg = df_neg.sample(frac=0.1, random_state=42)

In [6]:
df_out = pd.concat([df_pos, df_neg])
df_out['class'] = df_out['Pneumonia'].apply(lambda x: 1 if x == 1.0 else 0)

# Drop rows with missing or unknown gender
df_out = df_out[df_out['Sex'].isin(['Male', 'Female'])]
df_out['gender'] = df_out['Sex'].map({'Male': 0, 'Female': 1})

display(df_out.describe())
df_out

,Age,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,class,gender
count,4647.000000,720.0,882.000000,674.000000,2987.000000,349.000000,1527.000000,1628.000000,3960.000000,1011.000000,1016.000000,2075.000000,128.000000,179.000000,1529.000000,4647.000000,4647.000000
mean,60.168065,1.0,-0.080499,0.341246,0.848343,0.661891,0.343811,0.148649,0.991667,-0.122651,0.070866,0.465060,0.265625,0.480447,0.931982,0.845061,0.431246
std,19.261437,0.0,0.565048,0.730887,0.479415,0.665451,0.824152,0.773734,0.090917,0.981407,0.333510,0.661016,0.909135,0.544026,0.288213,0.361885,0.495304
min,18.000000,1.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000,0.000000
25%,47.000000,1.0,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,-1.000000,0.000000,0.000000,-1.000000,0.000000,1.000000,1.000000,0.000000
50%,62.000000,1.0,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,-1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
75%,76.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,90.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,...,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,patient_id,study_id,image,class,gender
311,CheXpert-v1.0-small/train/patient00085/study1/...,Male,88,Frontal,AP,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,patient00085,study1,train/patient00085/study1/view1_frontal.jpg,1,0
315,CheXpert-v1.0-small/train/patient00086/study1/...,Female,77,Frontal,AP,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,patient00086,study1,train/patient00086/study1/view1_frontal.jpg,1,1
390,CheXpert-v1.0-small/train/patient00112/study1/...,Male,35,Frontal,PA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,patient00112,study1,train/patient00112/study1/view1_frontal.jpg,1,0
411,CheXpert-v1.0-small/train/patient00114/study15...,Male,55,Frontal,AP,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,1.0,patient00114,study15,train/patient00114/study15/view1_frontal.jpg,1,0
440,CheXpert-v1.0-small/train/patient00122/study5/...,Female,72,Frontal,AP,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,1.0,patient00122,study5,train/patient00122/study5/view1_frontal.jpg,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44167,CheXpert-v1.0-small/train/patient10789/study1/...,Male,40,Frontal,AP,1.0,0.0,NaN,NaN,NaN,...,0.0,0.0,NaN,0.0,NaN,patient10789,study1,train/patient10789/study1/view1_frontal.jpg,0,0
166712,CheXpert-v1.0-small/train/patient38899/study1/...,Male,82,Frontal,AP,1.0,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,1.0,patient38899,study1,train/patient38899/study1/view1_frontal.jpg,0,0
214214,CheXpert-v1.0-small/train/patient57721/study1/...,Male,51,Frontal,AP,1.0,0.0,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,patient57721,study1,train/patient57721/study1/view1_frontal.jpg,0,0
54984,CheXpert-v1.0-small/train/patient13321/study1/...,Female,56,Frontal,PA,1.0,0.0,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,patient13321,study1,train/patient13321/study1/view1_frontal.jpg,0,1
101284,CheXpert-v1.0-small/train/patient24351/study1/...,Male,46,Frontal,PA,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,patient24351,study1,train/patient24351/study1/view1_frontal.jpg,0,0

In [7]:
df_out = df_out.sample(frac=1, random_state=42).reset_index(drop=True)
df_out = df_out.rename(columns={
    'Age': 'age',
    'AP/PA': 'view_pos'
})
df_out = df_out[['image', 'age', 'gender', 'view_pos', 'class']]
df_out

                                            image  age  gender view_pos  class
0     train/patient05052/study6/view1_frontal.jpg   83       0       PA      1
1     train/patient49541/study3/view1_frontal.jpg   90       1       AP      1
2     train/patient13994/study1/view1_frontal.jpg   73       1       PA      1
3     train/patient33914/study2/view1_frontal.jpg   58       0       AP      1
4     train/patient57085/study1/view1_frontal.jpg   79       1       AP      1
...                                           ...  ...     ...      ...    ...
4642  train/patient31273/study1/view1_frontal.jpg   31       0       PA      0
4643  train/patient06389/study6/view1_frontal.jpg   26       1       AP      1
4644  train/patient42250/study1/view1_frontal.jpg   56       1       AP      1
4645  train/patient58743/study1/view1_frontal.jpg   65       1       AP      1
4646  train/patient11653/study1/view1_frontal.jpg   76       0       PA      1

[4647 rows x 5 columns]

In [9]:
df_out.to_csv('../../data/CheXpert-v1.0-small_raw/experiment_data.csv', index=False)

## Prova d'entrenament:

In [11]:
import sys
from pathlib import Path
from dotenv import load_dotenv, find_dotenv

_env_file = find_dotenv()
REPO_DIR = Path(_env_file).parent.resolve()
load_dotenv(_env_file)
ROOT = (REPO_DIR / os.getenv("ROOT")).resolve()
os.chdir(ROOT)
sys.path.insert(0, str(ROOT))

from src.experiment_notebook import run_experiment

In [12]:
run_experiment(
    data_subdir='data/CheXpert-v1.0-small_raw',
    img_subdir='',
    results_base_dir='results/results_CheXpert',
    alpha=0.0,
)

Device: cpu
Config: alpha=0.0, layer_size=256, batch_size=32, lr=0.0001
Model: FeatureExtractor (no dropout)
Frozen params: 11,176,512  |  Trainable params: 131,842
Data: 3717 train / 930 test samples
Results dir: results/results_CheXpert/exp_256_alpha_0.0_20260505_231926

Running 100 iterations of 10 epochs each...
============================================================

--- Iteration 1/100 ---

KeyboardInterrupt: